[윤혜림] Sprint4
codeit-bootcamp-frontend/12-Sprint-Mission pull request #149
Opened 2024-11-13 10:14 UTC by y5037

##요구사항

>기본
- [x] Github에 PR(Pull Request)을 만들어서 미션을 제출합니다.
- [x] 피그마 디자인에 맞게 페이지를 만들어 주세요.
- [x] React와 같은 UI 라이브러리를 사용하지 않고 진행합니다.

>로그인
- [x] 이메일 input에서 focus out 할 때, 값이 없을 경우 input에 빨강색 테두리와 아래에 “이메일을 입력해주세요.” 빨강색 에러 메세지를 보입니다.
- [x] 이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 경우 input에 빨강색 테두리와 아래에 “잘못된 이메일 형식입니다” 빨강색 에러 메세지를 보입니다.
- [x] 비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해주세요.” 에러 메세지를 보입니다
- [x] 비밀번호 input에서 focus out 할 때, 값이 8자 미만일 경우 아래에 “비밀번호를 8자 이상 입력해주세요.” 에러 메세지를 보입니다.
- [x] input 에 빈 값이 있거나 에러 메세지가 있으면 ‘로그인’ 버튼은 비활성화 됩니다.
- [x] input 에 유효한 값을 입력하면 ‘로그인' 버튼이 활성화 됩니다.
- [x] 활성화된 ‘로그인’ 버튼을 누르면 “/items” 로 이동합니다

>회원가입
- [x] 이메일 input에서 focus out 할 때, 값이 없을 경우 input에 빨강색 테두리와 아래에 “이메일을 입력해주세요.” 빨강색 에러 메세지를 보입니다.
- [x] 이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 경우 input에 빨강색 테두리와 아래에 “잘못된 이메일 형식입니다” 빨강색 에러 메세지를 보입니다.
- [x] 닉네임 input에서 focus out 할 때, 값이 없을 경우 input에 빨강색 테두리와 아래에 “닉네임을 입력해주세요.” 빨강색 에러 메세지를 보입니다.
- [x] 비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해주세요.” 에러 메세지를 보입니다
- [x] 비밀번호 input에서 focus out 할 때, 값이 8자 미만일 경우 아래에 “비밀번호를 8자 이상 입력해주세요.” 에러 메세지를 보입니다.
- [x] 비밀번호 input과 비밀번호 확인 input의 값이 다른 경우, 비밀번호 확인 input 아래에 “비밀번호가 일치하지 않습니다..” 에러 메세지를 보입니다.
- [x] input 에 빈 값이 있거나 에러 메세지가 있으면 ‘회원가입’ 버튼은 비활성화 됩니다.
- [x] input 에 유효한 값을 입력하면 ‘회원가입' 버튼이 활성화 됩니다.
- [x] 활성화된 ‘회원가입’ 버튼을 누르면 “/signup” 로 이동합니다.

>체크리스트 [심화]
- [x] 눈 모양 아이콘 클릭시 비밀번호의 문자열이 보이기도 하고, 가려지기도 합니다.
- [x] 비밀번호의 문자열이 가려질 때는 눈 모양 아이콘에는 사선이 그어져있고, 비밀번호의 문자열이 보일 때는 사선이 없는 눈 모양 아이콘이 보이도록 합니다.

## 주요 변경사항
- focusout으로 이벤트 시 오류 메세지가 직관적이지 않은 거 같아 keyup으로 대체 했는데 문제가 된다면 수정하겠습니다.
- 스크립트 코드 구현이 미숙합니다. 개선할 수 있는 방안을 알려주신다면 적극적으로 반영하겠습니다.

## 스크린샷
<img width="2240" alt="스크린샷 2024-11-13 오후 7 12 39" src="https://github.com/user-attachments/assets/c79370d2-8cd2-4783-834a-4ee797e219ba">
<img width="2240" alt="스크린샷 2024-11-13 오후 7 13 03" src="https://github.com/user-attachments/assets/1a0747c3-7825-47d0-9108-a1b750bfee51">

## 멘토에게
- https://yunhyerim-pandamarket.netlify.app/

2024-11-14 03:08 UTC, 1005hoon requested changes
혜림님! 
전반적으로 자바스크립트를 최대한 잘 활용해주셨네요 
많이 고민하신게 보여요! 

다만 아직 관심사의 분리 차원에서 너무나도 많은 작업을 한번에 처리하는 함수들로 이루어져있다보니, 가독성은 물론 이후 기능 추가를 위한 유지보수 차원에서도 관리하기 어려운 함수들로 만들어져있습니다. 

우리 멘토링에서 이야기했던걸 한번 참고해서 기술기획부터 다시 한번 잡아나가보면 어떨까요? 
작업 마쳐주신 후, 우측 상단에서 리뷰어에게 다시 리뷰 요청하기 올려주시면 체크해드릴게요!

2024-11-14 03:08 UTC, 1005hoon commented on css/register.css
> +.formWrap input:required:focus{
음 지금 상황이면 required input이 focus인 경우에는 무조건 빨간 보더를 보여주고 있잖아요? 
그런데 생각해보면, 이 요소는 동적으로 들어왔다 빠졌다 할 수 있어야 할거에요.

따라서 우리 오늘 멘토링때 이야기 했던 관점에서 생각해보면 

```html
input[type="email"].form-group__input.input-error
```

정도로 만들어서 
```css
.input-error {
  border: ...
}
```

설정을 두어 input이 지닌 기본 스타일링을 가져가다가 `input__error` 라는 클래스를 자바스킓트로 동적으로 추가함으로써 에러 UI를 업데이트 하도록 해보면 어떨까요?

2024-11-14 03:08 UTC, 1005hoon commented on css/reset.css
> +  --red:#F74747;
색의 경우, 지금 어떤건 `color###` (gray100) 형태로 가져가고, 어떤건 `color` (red), 그리고 어떤건 `color[State]`(blueHover) 형태로 가져가고 있잖아요?

이런식으로 사용하기보단, 색을 위한 변수 네이밍도 통일해보면 좋겠어요

2024-11-14 03:08 UTC, 1005hoon commented on css/reset.css
> +  --red:#F74747;
예를들어, gray컬러처럼 템플릿 그레이딩이 필요한 요소라면 `--color-###` 형태로 가져가구, 
단 한가지 색이 필요한 단벌색의 경우 우리 브랜드의 주요 색상이라면 `--primary` `--primary-foreground` `--secondary` `--secondary-foreground` 형태로, 
단벌색이지만, 그냥 핵심 색으로 하나만 필요하다면 `--red` `--blue` ... 등으루 두고
만약 hover상태시 들어가는 색이라 하더라도, 이에 대한 관리는 해당 요소의 css에서 관리하고, 색상 자체에 대해서는 그냥 `--blue-light` 정도로 두어 활용하는게 더 적합하지 않을까 생각합니다.

2024-11-14 03:08 UTC, 1005hoon commented on js/default.js
핵심 로직을 조립하는 목적으로 이 파일을 두신거죠? 
컨벤션에 따라본다면, `app.js` `main.js` 또는 `index.js` 정도가 더 적합해 보입니다!

2024-11-14 03:08 UTC, 1005hoon commented on js/default.js
또한, 폴더 구조의 경우 지금 회원가입 기능을 작업하고 있다면 음.. 다음과 같이 폴더구조를 구성해보면 어떨까요? 
```
/signup
  /index.html
  /styles.css
  /scripts
    /index.js
    /validation.js
    /ui-controller.js
...
```

2024-11-14 03:08 UTC, 1005hoon commented on js/default.js
더 나아가 전반적으로 공통으로 활용되는 스크립트 파일이라면 

```
index.html
scripts
  /validation.js
/signup
  /index.html
  /styles.css
  /scripts
    /index.js
    /ui-controller.js
```

이런식으로 빼볼수도 있겠구요

2024-11-14 03:08 UTC, 1005hoon commented on js/register.js
> +export function focus(e){
이 함수의 역할이 무엇일지 한번 정리해볼까요? 

1. 타겟의 id와 값, 워닝메시지를 위한 요소를 꺼내와서
2. switch 기반으로 상당히 많은 요소들에 대한 로직처리를 해주고
3. 필요한 요소들을 체크해서 
4. 제출버튼 활성화 / 비활성화를 해주는

약간 어플리케이션의 모든 작업을 함수 하나에서 다 관리를 하고 있어요.

2024-11-14 03:08 UTC, 1005hoon commented on js/register.js
> +export function focus(e){
이렇게 코드가 작성이 되면, 특정 영역에 대해 사소한 수정을 하려고 해도, 이 함수 전체에 대한 동작을 이해하고 그 다음에야 기능 수정을 할 수 있을거에요. 따라서 함수는 가능한한 한가지 기능만 작업하도록 묶어두고, 관심사 차원에서 역할을 명확하게 제공하는게 좋지 않을까 생각해요

2024-11-14 03:08 UTC, 1005hoon commented on js/register.js
> +export function focus(e){
다시한번 우리 오늘 멘토링때 이야기했던것처럼 한번 기술기획구조를 한번 나누어보고 진행해볼까요?

2024-11-14 03:08 UTC, 1005hoon commented on js/source.js
source.js의 역할이 무엇일까요?
html DOM요소들을 저장하고, 이메일 체크하는 함수를 구현해 export 하는걸로 보이는데, 연관성을 찾아보기가 어렵습니다 ㅜㅜ

2024-11-14 07:33 UTC, y5037 commented on css/register.css
> +.formWrap input:required:focus{
required의 true, false 여부에 따라서 Script와 CSS로 input에 대한 에러 UI가 작동 하게끔 일괄적으로 구현이 된 부분인데 꼭 class를 사용해서 구현해야 하는 이유가 있을까요?

2024-11-14 08:44 UTC, 1005hoon commented on css/register.css
> +.formWrap input:required:focus{
@y5037 
좋은 질문입니다! 

`.formWrap input:required:focus` 의 선택자를 살펴보면 우선 다음과 같은 경우 `border:2px solid var(--red)`  스타일이 적용되어요:

1. input 요소가 HTML5의 required 속성을 가지고 있고
2. input 요소가 포커스를 받고 있을때 

따라서 입력이 필수인데 입력을 하지 않고 폼을 제출했을때 required 요소까지는 적용되지만 input이 focus가 되지 않은 요소에게는 이 오류 피드백이 보여지지 않죠. 

따라서 만약 이메일과 비밀번호 둘 다 입력하지 않고 폼을 제출했다고 하면, 이메일 인풋과 비밀번호 인풋 둘 중 어떤거에 이 빨간 테두리가 적용될까요?

2024-11-14 08:45 UTC, 1005hoon commented on css/register.css
> +.formWrap input:required:focus{
더 나아가서, 특정한 경우에는 입력이 필수인 케이스 외에도 
우리가 지정한 형태의 이메일인지, 또는 우리가 설정한 비밀번호 제한사항을 달성하는지 등에 따라서 해당 요소에게 빨간 보더를 제공하여 오류임을 유저에게 피드백해주어야 합니다. 

따라서 이런 범용적인 케이스를 달성할 수 있도록, css 클래스로 해당 스타일을 제공하고, JavaScript를 활용해 동적으로 필요상황에 따라 해당 스타일을 적용시키는게 조금 더 다양한 경우의 수를 커버하기에도 수월할거에요

2024-11-14 09:15 UTC, y5037 commented on css/register.css
> +.formWrap input:required:focus{
'따라서 만약 이메일과 비밀번호 둘 다 입력하지 않고 폼을 제출했다고 하면, 이메일 인풋과 비밀번호 인풋 둘 중 어떤거에 이 빨간 테두리가 적용될까요?' 이렇게 피드백 주신 부분에 있어서는 이미 CSS의 :required:focus 와 script의 focus 이벤트로 조건이 맞지 않으면 폼을 제출하지 못하도록 구현을 한 부분이라서 이해가 잘 안됩니다..ㅜㅜ

2024-11-15 09:00 UTC, y5037 commented
<코드 리뷰 재요청 변경 사항>
1. [source.js]
-> 해당 파일의 역할이  불분명하다고 판단 되어 삭제 처리 하였습니다. 말씀 해주신 폴더구조 구성에 따라 이메일 유효성 체크는 공통 validation.js로 이동하였습니다.
2. [CSS 색상 변수명 통일]
-> 코드리뷰 해주신 내용대로 정리 되었습니다.
3. [폴더구조]
-> 코드리뷰 해주신 내용대로 정리 되었습니다.
4. [Error UI]
-> 사용자의 관점에서 보다 더 직관적으로 에러 사항을 확인하고, 필요한 동작을 수행할 수 있도록 Error UI 관련 코드가 추가 되었습니다.

2024-11-15 09:48 UTC, y5037 commented
<코드 리뷰 재요청 변경 사항>

[source.js]
-> 해당 파일의 역할이 불분명하다고 판단 되어 삭제 처리 하였습니다. 말씀 해주신 폴더구조 구성에 따라 이메일 유효성 체크는 공통 validation.js로 이동하였습니다.
[CSS 색상 변수명 통일]
-> 코드리뷰 해주신 내용대로 정리 되었습니다.
[폴더구조]
-> 코드리뷰 해주신 내용대로 정리 되었습니다.
[Error UI]
-> 사용자의 관점에서 보다 더 직관적으로 에러 사항을 확인하고, 필요한 동작을 수행할 수 있도록 Error UI 관련 코드가 추가 되었습니다.

2024-11-19 23:48 UTC, 1005hoon approved these changes
혜림님! 초반 피드백부터 너무 잘해주시고 계십니다.

쉽지 않은 개편사항이였을텐데 리뷰 최대한 반영해가면서 지속적으로 질문주시고 개선시키신거 좋았어요.

다만 몇가지 우려되는 부분이 있는데요, 첫째로 말씀드리고 싶은게, 코드는 명확하게 작성될수록 좋은 코드입니다. 어떻게든 한줄로 묶어서 로직을 구현한것 보다 단순하게 풀어 작성을 해서 몇십줄의 코드로  작성한게 유지보수 차원에서 가독성이 훨씬 좋기 때문이에요. 작성하신 코드에서 부분부분 최대한 간추려서 작성하고자 하는 의도들이 보여 염려되어 말씀드려봅니다. 

둘째로, 함수는 하나의 추상화된 인터페이스의 기능을 제공해줍니다.
표현이 조금 어려운데요, 멘토링때 이야기했던것처럼 함수의 이름과 매개변수들, 그리고 함수가 반환하는 값을 기준으로 모든 개발자들이 해당 함수가 제공하는 기능과 담당하는 역할과 책임을 분명하게 알 수 있어야 해요. 예를들어, 착즙기를 만들었다고 하면, 착즙기 입구가 있고 누가봐도 과일을 넣을수 있게 하고, 출력되는건 과일 쥬스가 나오게 한다면 어떤 모양으로 만들엇든 사람들이 착즙기의 역할과 책임을 알고 그에 맞게 적절하게 사용하잖아요? 함수도 마찬가지입니다. 함수의 존재 의의를 한번 고민해보고 코드 구성을 해보는게 아마 큰 도움이 될 수 있지 않을까 생각해요.

자세한 리뷰는 코드단에 남겨두었으니 참고 부탁드립니다.
고생 많으셨어요!

2024-11-19 23:48 UTC, 1005hoon commented on css/register.css
> +.formWrap input:required:focus{
그래서 조금만 더 정리를 해본다면, 

**유지보수성과 확장성의 관점에서**
현재 코드에서는 :required와 :focus 상태를 조합하여 스타일을 적용하고 있지만, 이런 접근은 유지보수 측면에서 단점이 있습니다. 에러 처리를 위해 _추가적인 조건_이 생긴다면 CSS 상태 셀렉터만으로 이를 표현하기 어려워질 수 있습니다. 반면, 클래스 기반 접근은 스크립트를 통해 다양한 상황(예: 비동기 검증 결과, 사용자 인터랙션 등)에 유연하게 대응할 수 있습니다.

예를 들어, input이 서버에서 검증을 통과하지 못한 경우, required 상태가 아니라도 에러 스타일이 필요할 수 있습니다. 이 경우 상태 셀렉터만으로는 처리가 어려우며, 클래스 기반 접근이 더 적합합니다.

**의미를 명확히 전달하기 위해**
:required:focus는 "필수 필드"임과 동시에 "포커스 상태"라는 조건에만 의존합니다. 
하지만 실제 에러가 발생했는지를 명확히 표현하려면, input-error와 같은 명시적인 클래스명을 사용하는 것이 좋습니다. 이를 통해 CSS만 보더라도 해당 요소가 에러 상태임을 어떤 개발자가 봐도 쉽게 이해할 수 있을거에요.
특히 클래스명을 통해 의미를 전달하는 것은 코드의 가독성과 팀 협업에도 유리하답니다.

**동적 변경의 유연성**
JavaScript를 활용해 특정 요소에 input-error 클래스를 추가하거나 제거하면, 상태에 따라 UI를 동적으로 더 유연하게 업데이트 시킬 수 있어요

예를들어:
1. 포커스가 없어도 에러 표시가 유지되어야 하는 경우.
2. 그 외 특정 조건에 따라 input-error 클래스 추가/제거.

2024-11-19 23:48 UTC, 1005hoon commented on css/register.css
> +.formWrap input:required:focus{
아, 제가 이야기 했던 케이스는 폼을 제출했을때 required field가 입력되지 않았다면 해당 위치로 자동 포커스를 해주는 동작을 이야기했던거에요. 제가 자바스크립트로 위에 이야기 한 경우를 막으신걸 확인하지 않고 예시를 드렸네요. 다만 우려되는 부분들은 아래 설명한 내용과 같습니다:

혜림님 이야기를 정리해보면, 지금 현 상황은 `자바스크립트로 email / password둘다 입력이 된 후에 제출할수 있도록 구현이 되어있다` 인거죠? 

우선 요구사항을 살펴보면 email / password 인풋에 `focus out`할때 값이 없으면 빨갛게 색을 제공해야 한다고 하고 있습니다.
![image](https://github.com/user-attachments/assets/7e65f032-b0b3-497c-a048-21fa3eb8b3cf)

그리고 제대로 된 값이 입력되었을때는 요구사항에 적혀있지 않지만, 다음 이미지와 같이 푸른색으로 보여져야 하는듯 하구요 
![image](https://github.com/user-attachments/assets/32362bd4-36e4-48dc-b170-80cff9ba3803)

그러나 지금처럼 `:required:focus` 로 설정했을땐 required가 적용된 Input들에 focus 이벤트가 발생하면 오류가 아닌 상태임에도 불구하고 무조건 빨간색으로 색이 지정되도록 스타일 선언이 되어있어요
![image](https://github.com/user-attachments/assets/b17949ee-3d0c-4cd5-9cfb-5fa49cfebe90)

2024-11-19 23:48 UTC, 1005hoon commented on css/register.css
> +.formWrap input:required:focus{
따라서 input required요소들에게 기본적으로 값을 입력하는 동안에는 focus되어있음을 보여주고 (이거는 지금 피그마 시안에도 이야기가 없고, 요구사항에도 적혀있지는 않습니다)

입력을 마친 후 `focus out` 이벤트를 발생시킨 그 상황에, 값이 오류를 포함하고 있다면 빨간색 보더가 주어지도록 설정하고, 제대로 된 값이 입력되었다면 파란색 보더가 주어지도록 (이것도 요구사항에는 없지만 피그마 시안에는 그려져 있는것으로 보입니다) 설정해야 하는것으로 보입니다. 

따라서 지금 구현된 `input:required:focus` 의 경우, 모든 required input에게 focus되었을때 오류 여부와는 상관없이 무조건 빨간색으로 보여주고 있기 때문에 다른 방식으로 기능을 제공해보는게 필요하다 이야기를 드리고 싶어요.

2024-11-19 23:48 UTC, 1005hoon commented on css/reset.css
> +  --primary-foreground:#1967D6;
너무 좋습니다

2024-11-19 23:48 UTC, 1005hoon commented on css/styles.css
>      @media (min-width:375px) and (max-width: 767px){
문득 궁금한게 있는데요, 
css preprocessor를 사용하지 않는데, class 내부에 미디어쿼리를 중첩해도 잘 동작 하나요? 
제가 기억하기로는 css에서는 미디어 쿼리가 최 상단에 있어야 하는걸로 (nested 되지 않도록) 이해하고 있는데, 바뀐 스펙이 있는가 싶어 여쭤봅니다

2024-11-19 23:48 UTC, 1005hoon commented on js/validation.js
> +export function emailCheck(email) {
유효성을 체크하고는 있지만, 우리 멘토링에서 이야기했던것처럼 클린코드 관점에서 
명확하게 이 함수가 어떤 동작을 실행하고, 어떤 결과를 반환해줄지 예측할 수 있는 네임으로 업데이트 해볼까요?

2024-11-19 23:48 UTC, 1005hoon commented on js/validation.js
> +    let regex=/([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
이 Regex는 변경될 여지가 없어보입니다! 따라서 const로 정의해보면 어떨까 싶어요

2024-11-19 23:48 UTC, 1005hoon commented on js/validation.js
> +    return (email != '' && email != 'undefined' && regex.test(email));
이렇게 체크 로직을 한줄로 묶어쓰는게 뭐랄까 편의성이 좋고, 심미성이 좋아보이긴 하지만 
이후 유지보수 차원에서의 가독성은 좋지 않습니다! 이 로직들이 체크하고 있는게 뭔지 파악하기 위해서는 왼쪽 return (부터 가장 오른쪽에 있는 로직까지 다 읽어야만 이해할  수 있기 때문인데요.

이를 개편하기 위해 번거롭더라도 굳이 if / else를 사용해주시는걸 지금 단계에서는 추천드립니다 
특히, 명확하게 어떤 경우들을 우리가 잘못된 이메일로 평가할건지를 파악하기 쉽게 한다는 목적으로 명시적으로 작성해주는게 더 도움이 될거에요

2024-11-19 23:48 UTC, 1005hoon commented on js/validation.js
> +    return (email != '' && email != 'undefined' && regex.test(email));
또한 자바스크립트에서 `==` `!=`와 `===` `!==` 는 아주 큰 차이가 있답니다.
지금은 primitive value를 비교하기 때문에 큰 문제는 없었지만, 되도록이면 `===` 와 `!==` 를 사용하는 습관을 가져주시면 좋겠어요!

2024-11-19 23:48 UTC, 1005hoon commented on signup/js/index.js
> +};
이후 프로젝트들이 복잡해지게 되는 경우, 
단순 로그인 / 회원가입을 위한 이메일 비밀번호 인풋만 존재하지 않게 되는 경우도 많습니다. 
따라서 모든 inputList에게 배열로 돌면서 일괄적으로 동일한 함수를 적용하기보단
좀 더 명시적으로 어떤 인풋에게는 어떤 이벤트에 대한 핸들링을 어떻게 적용할건지 작성해주는게 조금 더 관리차원에서 수월하실거에요

2024-11-19 23:48 UTC, 1005hoon commented on signup/js/index.js
> +};
이 경우에도 조금 고민해보면 

toggle-visibility-btn 을 하나 두고, 버튼 토글시마다 이미지만 바뀌게 한다면 버튼 하나를 DOM요소 선택자로 두어 onClick 이벤트 발생시마다 이미지와 비밀번호 input의 type을 바꿔주는식으로 구현해볼 수 있겠어요

2024-11-19 23:48 UTC, 1005hoon commented on signup/js/ui-controller.js
ui-controller의 목적을 생각해보면 DOM요소를 조작하는 함수들이 들어가게 되겠죠?
하지만, 실제 DOM 요소를 조작시키는 로직은 우리 어플리케이션의 주요 로직에서 실행이 되는게 좋습니다!

2024-11-19 23:48 UTC, 1005hoon commented on signup/js/ui-controller.js
> +function userInform(e){
userInform이라는 함수가 처리하는 역할이 너무나도 많네요 

`errorContext` `inputError` `inputComplet <오타있어보입니다!` 함수에 대한 정의를 하고,

전달받은 요소의 id를 기준으로 switch를 돌리며 
`email`인 경우 3가지 밸리데이션을 진행
`password`인 경우 또 여러 밸리데이션 진행
...

등등 너무 많은 작업들을 한곳에서 관리하고 있지요.

2024-11-19 23:48 UTC, 1005hoon commented on signup/js/ui-controller.js
> +function userInform(e){
우리가 멘토링에서 이야기했을때, 코드는 최대 한가지 기능만 명확하게 하도록 하는게 좋다고 이야기를 했었어요. 
클린코드에서 설명하는 [single responsibility principle](https://duncan-mcardle.medium.com/solid-principle-1-single-responsibility-javascript-5d9ce2c6f4a5)이라는 개념인데요, 멘토링에서 예시로 보여드렸다싶이, 역할과 책임이 명확하게 구분된다면 
해당 함수 자체의 가독성 / 유지보수 차원에서 다른 개발자들이 맥락파악하기도 수월할 뿐만 아니라 
동시에 작업을 한다 하더라도 명확하게 영역이 구분되기 때문에 컨플릭이 발생할 여지도 적답니다. 
한번 이 함수를 어떻게 각자의 역할과 책임에 따라 달라지게 하면 좋을지 고민해볼까요?

2024-11-20 00:21 UTC, merged